/**
 * Generated by tsnapi — public API snapshot of `@stephansama/ai-commit-msg/schema`
 */
// #region Types
export type Config = Partial<z.infer<typeof configSchema>>;
export type Model = (typeof models)[number];
export type Provider = (typeof providers)[number];
// #endregion

// #region Variables
export declare const configSchema: z.ZodObject<{
  baseURL: z.ZodOptional<z.ZodString>;
  headers: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodString>>;
  model: z.ZodString;
  prompt: z.ZodDefault<z.ZodString>;
  provider: z.ZodEnum<{
    google: "google";
    openai: "openai";
    ollama: "ollama";
  }>;
  skipNextRun: z.ZodOptional<z.ZodBoolean>;
  useConventionalCommits: z.ZodDefault<z.ZodBoolean>;
  verbose: z.ZodDefault<z.ZodUnion<readonly [z.ZodLiteral<0>, z.ZodLiteral<1>, z.ZodLiteral<2>, z.ZodLiteral<3>]>>;
}, z.core.$strip>;
export declare const defaultPrompt: string;
export declare const environmentSchema: {
  google: z.ZodObject<{
    GOOGLE_GENERATIVE_AI_API_KEY: z.ZodString;
  }, z.core.$strip>;
  ollama: z.ZodObject<{}, z.core.$strip>;
  openai: z.ZodObject<{
    OPENAI_API_KEY: z.ZodString;
  }, z.core.$strip>;
};
export declare const models: readonly ["gemini-2.5-flash"];
export declare const providers: readonly ["google", "openai", "ollama"];
export declare const providerSchema: z.ZodEnum<{
  google: "google";
  openai: "openai";
  ollama: "ollama";
}>;
// #endregion