/**
 * Generated by tsnapi — public API snapshot of `@stephansama/typed-templates`
 */
// #region Types
export type HandlebarSchemaMapOptions = {
  path: string;
  schema: StandardSchemaV1;
};
// #endregion

// #region Functions
export declare function createHandlebarSchemaMap<Map extends Record<string, HandlebarSchemaMapOptions>>(_: Map, _: {
  templateDirectory: string;
}): {
  audit(): Promise<boolean>;
  compile<Key extends keyof Map & string>(_: Key, _: StandardSchemaV1.InferInput<(typeof map)[Key]["schema"]>): Promise<string>;
  map: Map;
};
export declare function createHandlebarSchemaSingleton<const Files extends readonly string[], Schema extends StandardSchemaV1, File = Files[number]>(_: Files, _: Schema, _?: {
  templateDirectory: string;
}): {
  audit(): Promise<boolean>;
  compile(_: File & string, _: StandardSchemaV1.InferInput<Schema>): Promise<string>;
  files: Files;
};
export declare function getFileContext(_?: string): {
  isLinting: () => boolean;
  templateDirectory: string;
};
// #endregion