/**
 * This file was automatically generated by json-schema-to-typescript. DO NOT
 * MODIFY IT BY HAND. Instead, modify the source JSONSchema file, and run
 * json-schema-to-typescript to regenerate this file.
 */

/** E.g. 2014-06-29 */
export type Iso8601 = string;

export interface ResumeSchema {
	/** Link to the version of the schema that can validate the resume */
	$schema?: string;
	/** Specify any awards you have received throughout your professional career */
	awards?: {
		[k: string]: unknown;
		/** E.g. Time Magazine */
		awarder?: string;
		date?: Iso8601;
		/** E.g. Received for my work with Quantum Physics */
		summary?: string;
		/** E.g. One of the 100 greatest minds of the century */
		title?: string;
	}[];
	basics?: {
		[k: string]: unknown;
		/** E.g. thomas@gmail.com */
		email?: string;
		/** URL (as per RFC 3986) to a image in JPEG or PNG format */
		image?: string;
		/** E.g. Web Developer */
		label?: string;
		location?: {
			[k: string]: unknown;
			/**
			 * To add multiple address lines, use . For example, 1234
			 * Glücklichkeit Straße Hinterhaus 5. Etage li.
			 */
			address?: string;
			city?: string;
			/** Code as per ISO-3166-1 ALPHA-2, e.g. US, AU, IN */
			countryCode?: string;
			postalCode?: string;
			/**
			 * The general region where you live. Can be a US state, or a
			 * province, for instance.
			 */
			region?: string;
		};
		name?: string;
		/**
		 * Phone numbers are stored as strings so use any format you like, e.g.
		 * 712-117-2923
		 */
		phone?: string;
		/** Specify any number of social networks that you participate in */
		profiles?: {
			[k: string]: unknown;
			/** E.g. Facebook or Twitter */
			network?: string;
			/** E.g. http://twitter.example.com/neutralthoughts */
			url?: string;
			/** E.g. neutralthoughts */
			username?: string;
		}[];
		/** Write a short 2-3 sentence biography about yourself */
		summary?: string;
		/** URL (as per RFC 3986) to your website, e.g. personal homepage */
		url?: string;
	};
	/**
	 * Specify any certificates you have received throughout your professional
	 * career
	 */
	certificates?: {
		[k: string]: unknown;
		/** E.g. 1989-06-12 */
		date?: string;
		/** E.g. CNCF */
		issuer?: string;
		/** E.g. Certified Kubernetes Administrator */
		name?: string;
		/** E.g. http://example.com */
		url?: string;
	}[];
	education?: {
		[k: string]: unknown;
		/** E.g. Arts */
		area?: string;
		/** List notable courses/subjects */
		courses?: string[];
		endDate?: Iso8601;
		/** E.g. Massachusetts Institute of Technology */
		institution?: string;
		/** Grade point average, e.g. 3.67/4.0 */
		score?: string;
		startDate?: Iso8601;
		/** E.g. Bachelor */
		studyType?: string;
		/** E.g. http://facebook.example.com */
		url?: string;
	}[];
	interests?: {
		[k: string]: unknown;
		keywords?: string[];
		/** E.g. Philosophy */
		name?: string;
	}[];
	/** List any other languages you speak */
	languages?: {
		[k: string]: unknown;
		/** E.g. Fluent, Beginner */
		fluency?: string;
		/** E.g. English, Spanish */
		language?: string;
	}[];
	/** The schema version and any other tooling configuration lives here */
	meta?: {
		[k: string]: unknown;
		/** URL (as per RFC 3986) to latest version of this document */
		canonical?: string;
		/** Using ISO 8601 with YYYY-MM-DDThh:mm:ss */
		lastModified?: string;
		/** A version field which follows semver - e.g. v1.0.0 */
		version?: string;
	};
	/** Specify career projects */
	projects?: {
		[k: string]: unknown;
		/** Short summary of project. e.g. Collated works of 2017. */
		description?: string;
		endDate?: Iso8601;
		/**
		 * Specify the relevant company/entity affiliations e.g. 'greenpeace',
		 * 'corporationXYZ'
		 */
		entity?: string;
		/** Specify multiple features */
		highlights?: string[];
		/** Specify special elements involved */
		keywords?: string[];
		/** E.g. The World Wide Web */
		name?: string;
		/** Specify your role on this project or in company */
		roles?: string[];
		startDate?: Iso8601;
		/**
		 * E.g. 'volunteering', 'presentation', 'talk', 'application',
		 * 'conference'
		 */
		type?: string;
		/** E.g. http://www.computer.org/csdl/mags/co/1996/10/rx069-abs.html */
		url?: string;
	}[];
	/** Specify your publications through your career */
	publications?: {
		[k: string]: unknown;
		/** E.g. The World Wide Web */
		name?: string;
		/** E.g. IEEE, Computer Magazine */
		publisher?: string;
		releaseDate?: Iso8601;
		/**
		 * Short summary of publication. e.g. Discussion of the World Wide Web,
		 * HTTP, HTML.
		 */
		summary?: string;
		/**
		 * E.g.
		 * http://www.computer.org.example.com/csdl/mags/co/1996/10/rx069-abs.html
		 */
		url?: string;
	}[];
	/** List references you have received */
	references?: {
		[k: string]: unknown;
		/** E.g. Timothy Cook */
		name?: string;
		/**
		 * E.g. Joe blogs was a great employee, who turned up to work at least
		 * once a week. He exceeded my expectations when it came to doing
		 * nothing.
		 */
		reference?: string;
	}[];
	/** List out your professional skill-set */
	skills?: {
		[k: string]: unknown;
		/** List some keywords pertaining to this skill */
		keywords?: string[];
		/** E.g. Master */
		level?: string;
		/** E.g. Web Development */
		name?: string;
	}[];
	volunteer?: {
		[k: string]: unknown;
		endDate?: Iso8601;
		/** Specify accomplishments and achievements */
		highlights?: string[];
		/** E.g. Facebook */
		organization?: string;
		/** E.g. Software Engineer */
		position?: string;
		startDate?: Iso8601;
		/** Give an overview of your responsibilities at the company */
		summary?: string;
		/** E.g. http://facebook.example.com */
		url?: string;
	}[];
	work?: {
		[k: string]: unknown;
		/** E.g. Social Media Company */
		description?: string;
		endDate?: Iso8601;
		/** Specify multiple accomplishments */
		highlights?: string[];
		/** E.g. Menlo Park, CA */
		location?: string;
		/** E.g. Facebook */
		name?: string;
		/** E.g. Software Engineer */
		position?: string;
		startDate?: Iso8601;
		/** Give an overview of your responsibilities at the company */
		summary?: string;
		/** E.g. http://facebook.example.com */
		url?: string;
	}[];
}
