packages:
  - lib/*
  - examples/**
  - packages/*
catalog:
  "@catppuccin/palette": "^1.7.1"
  nodemon: ^3.1.10
  tsup: ^8.3.6
  typescript: ^5.8.3
  vite: ^6.3.5
  vitest: ^3.2.4
  "@vitest/ui": ^3.2.4
  "@vitest/coverage-v8": ^3.2.4
  zx: ^8.5.5
catalogs:
  astro:
    "@astrojs/check": ^0.9.4
    astro: ^5.9.3
