packages:
  - ./.config/*
  - core/**
  - examples/**

autoInstallPeers: true

catalog:
  '@catppuccin/palette': 1.7.1
  '@dotenvx/dotenvx': ^1.52.0
  '@iconify/types': ^2.0.0
  '@iconify/utils': ^2.3.0
  '@manypkg/find-root': ^3.1.0
  '@manypkg/get-packages': ^3.1.0
  '@testing-library/jest-dom': ^6.9.1
  '@testing-library/react': ^16.3.2
  '@types/debug': ^4.1.12
  '@types/mdast': ^4.0.4
  '@types/minify': 9.1.4
  '@types/react': ^19.2.14
  '@types/vfile': ^4.0.0
  '@types/yargs': ^17.0.35
  astro: 5.9.3
  deepmerge: ^4.3.1
  es-toolkit: 1.43.0
  handlebars: 4.7.8
  happy-dom: ^20.6.1
  jsr: ^0.13.5
  mdast: ^3.0.0
  minify: 14.0.0
  node-plop: ^0.32.3
  prettier: ^3.8.1
  react: 19.2.0
  remark: ^15.0.1
  tsdown: 0.15.12
  tsx: 4.21.0
  typescript: 5.9.3
  undici: ^7.22.0
  unified: ^11.0.5
  unist-util-visit: ^5.1.0
  vite: 6.3.5
  vite-tsconfig-paths: ^5.1.4

catalogMode: strict

catalogs:
  cli:
    cosmiconfig: 9.0.0
    obug: 2.1.1
    yargs: 18.0.0
  schema:
    '@standard-schema/spec': ^1.1.0
    arktype: 2.1.29
    valibot: 1.2.0
    zod: 4.2.1
  storybook:
    '@chromatic-com/storybook': ^4.1.3
    '@storybook/addon-a11y': ^10.2.8
    '@storybook/addon-docs': ^10.2.8
    '@storybook/addon-svelte-csf': ^5.0.11
    '@storybook/svelte-vite': ^10.2.8
    storybook: ^10.2.8
  svelte:
    '@sveltejs/package': ^2.5.7
    '@sveltejs/vite-plugin-svelte': ^6.2.4
    '@tsconfig/svelte': ^5.0.7
    svelte: ^5.51.2
    svelte-check: ^4.4.0
  vitest:
    '@vitest/coverage-v8': ^4.0.18
    '@vitest/ui': ^4.0.18
    vitest: ^4.0.18

cleanupUnusedCatalogs: true

engineStrict: true

ignoredBuiltDependencies:
  - '@swc/core'
  - core-js-pure
  - sharp
  - workerd

onlyBuiltDependencies:
  - esbuild

overrides:
  '@stephansama/astro-iconify-svgmap': workspace:*
  '@stephansama/catppuccin-xsl': workspace:*
  '@stephansama/remark-asciinema': workspace:*
  '@stephansama/svelte-social-share-links': workspace:*
  '@stephansama/typed-events': workspace:*
  create-stephansama-example: workspace:*

shellEmulator: true
