packages:
  - ./.config/*
  - core/**
  - examples/**
autoInstallPeers: true
catalogMode: strict
cleanupUnusedCatalogs: true
engineStrict: true
shellEmulator: true
catalog:
  "@catppuccin/palette": 1.7.1
  "@testing-library/react": ^16.3.0
  "@testing-library/dom": ^10.4.1
  "@testing-library/jest-dom": ^6.9.1
  "@types/minify": 9.1.4
  "@types/react": ^19.2.2
  astro: 5.9.3
  handlebars: 4.7.8
  happy-dom: ^20.0.11
  minify: 14.0.0
  prettier: ^3.6.2
  react: 19.2.0
  tsdown: 0.15.12
  typescript: 5.9.3
  vite: 6.3.5
  vite-tsconfig-paths: ^5.1.4
  zod: 4.0.15
  zx: 8.8.0
ignoredBuiltDependencies:
  - "@swc/core"
  - core-js-pure
  - sharp
  - workerd
onlyBuiltDependencies:
  - esbuild
overrides:
  "@stephansama/astro-iconify-svgmap": workspace:*
  "@stephansama/catppuccin-xsl": workspace:*
  "@stephansama/remark-asciinema": workspace:*
  "@stephansama/svelte-social-share-links": workspace:*
  "@stephansama/typed-events": workspace:*
  create-stephansama-example: workspace:*
