packages:
  - ./.config/*
  - core/*
  - examples/**
autoInstallPeers: true
catalog:
  "@catppuccin/palette": ^1.7.1
  astro: ^5.9.3
  handlebars: ^4.7.8
  minify: "^14.0.0"
  tsup: ^8.3.6
  typescript: ^5.8.3
  vite: ^6.3.5
  vitest: ^3.2.4
  zod: ^4.0.15
  zx: ^8.8.0
engineStrict: true
overrides:
  "@stephansama/astro-iconify-svgmap": workspace:*
  "@stephansama/catppuccin-rss": workspace:*
  "@stephansama/remark-asciinema": workspace:*
  "@stephansama/typed-events": workspace:*
  "create-stephansama-example": workspace:*
