/**
 * Generated by tsnapi — public API snapshot of `@stephansama/typed-events/errors`
 */
// #region Classes
export declare class TypedBroadcastChannelError extends ValidatorError {
  constructor(_: string, _: readonly StandardSchemaV1.Issue[]);
}
export declare class TypedBroadcastEventError extends ValidatorError {
  constructor(_: string, _: readonly StandardSchemaV1.Issue[]);
}
export declare class TypedEventError extends ValidatorError {
  constructor(_: string, _: readonly StandardSchemaV1.Issue[]);
}
export declare class TypedMessageError extends ValidatorError {
  constructor(_: string, _: readonly StandardSchemaV1.Issue[]);
}
// #endregion