/**
 * Generated by tsnapi — public API snapshot of `@stephansama/typed-events`
 */
// #region Interfaces
export interface TypedBroadcastChannel<Name extends string, Map extends Record<string, StandardSchemaV1>> extends ValidatorMap<Name, Map, "message"> {
  readonly channel: BroadcastChannel;
}
export interface TypedBroadcastEvent<Name extends string, Map extends Record<string, StandardSchemaV1>> extends ValidatorMap<Name, Map, "event" | "message"> {
  readonly channel: BroadcastChannel;
  target: EventTarget;
}
export interface TypedEvent<Name extends string, Schema extends StandardSchemaV1> extends Validator<Name, Schema, "event"> {
  target: EventTarget;
}
export interface TypedEventMap<Name extends string, Map extends Record<string, StandardSchemaV1>> extends ValidatorMap<Name, Map, "event"> {
  target: EventTarget;
}
export interface Validator<Name extends string, Schema extends StandardSchemaV1, EventTypeKeys extends keyof RawEventMap, DispatchOptions = {}, Input = object & StandardSchemaV1.InferInput<Schema>> {
  dispatch(_: Input, _?: DispatchOptions): void;
  listen(_: ListenerCallback<Input, EventTypeKeys>): () => void;
  name: Name;
  schema: Schema;
}
export interface ValidatorMap<Name extends string, Map extends Record<string, StandardSchemaV1>, EventTypeKeys extends keyof RawEventMap, DispatchOptions = {}> {
  dispatch<Event extends keyof Map & string, Input extends object & StandardSchemaV1.InferInput<Map[Event]>>(_: Event, _: Input, _?: DispatchOptions): void;
  listen<Event extends keyof Map & string, Input extends object & StandardSchemaV1.InferInput<Map[Event]>>(_: Event, _: ListenerCallback<Input, EventTypeKeys>): () => void;
  map: Map;
  name: Name;
}
// #endregion

// #region Types
export type ListenerCallback<Input, Keys extends keyof RawEventMap> = (_: AnyPayload<Input, Keys>) => void;
export type RawEventMap<Shape = unknown> = {
  event: CustomEvent<Shape>;
  message: MessageEvent<Shape>;
};
export type Restrict<T extends string, Forbidden> = T extends Forbidden ? never : T;
// #endregion

// #region Functions
export declare function createBroadcastChannel<Name extends string, Map extends Record<string, StandardSchemaV1>>(_: Name, _: Map): {
  readonly channel: BroadcastChannel;
  dispatch<Event extends keyof Map & string, Input extends object & StandardSchemaV1.InferInput<Map[Event]>>(_: Event, _: Input): void;
  listen<Event extends keyof Map & string, Input extends object & StandardSchemaV1.InferInput<Map[Event]>>(_: Event, _: ListenerCallback<Input, "message">): () => void;
  map: Map;
  name: Name;
};
export declare function createBroadcastEvent<Name extends string, Map extends Record<string, StandardSchemaV1>>(_: Name, _: Map): {
  readonly channel: BroadcastChannel;
  dispatch<Event extends keyof Map & string, Input extends object & StandardSchemaV1.InferInput<Map[Event]>>(_: Event, _: Input): void;
  listen<Event extends keyof Map & string, Input extends object & StandardSchemaV1.InferInput<Map[Event]>>(_: Event, _: ListenerCallback<Input, "event" | "message">): () => void;
  map: Map;
  name: Name;
  target: EventTarget;
};
export declare function createEvent<Name extends Restrict<string, keyof DocumentEventMap>, Schema extends StandardSchemaV1>(_: Name, _: Schema, _?: {
  silenceAsyncWarning?: boolean;
  target?: EventTarget;
}): {
  dispatch(_: object & StandardSchemaV1.InferInput<Schema>): void;
  listen(_: ListenerCallback<object & StandardSchemaV1.InferInput<Schema>, "event">): () => void;
  name: Name;
  schema: Schema;
  target: EventTarget;
};
export declare function createEventMap<Name extends string, Map extends Record<string, StandardSchemaV1>>(_: Name, _: Map): {
  dispatch<Event extends keyof Map & string, Input extends object & StandardSchemaV1.InferInput<Map[Event]>>(_: Event, _: Input): void;
  listen<Event extends keyof Map & string, Input extends object & StandardSchemaV1.InferInput<Map[Event]>>(_: Event, _: ListenerCallback<Input, "event">): () => void;
  map: Map;
  name: Name;
  target: EventTarget;
};
export declare function createMessage<Name extends string, Map extends Record<string, StandardSchemaV1>>(_: Name, _: Map): {
  dispatch<Event extends keyof Map & string, Input extends object & StandardSchemaV1.InferInput<Map[Event]>>(_: Event, _: Input, _?: {
    origin: string;
    window: Window;
  } | undefined): void;
  listen<Event extends keyof Map & string, Input extends object & StandardSchemaV1.InferInput<Map[Event]>>(_: Event, _: ListenerCallback<Input, "message">): () => void;
  map: Map;
  name: Name;
  window: Window;
};
// #endregion

// #region Other
export { StandardSchemaV1 }
// #endregion