/**
 * Generated by tsnapi — public API snapshot of `@stephansama/typed-events/react`
 */
// #region Functions
export declare function useListener<Name extends string, Input extends Validator<Name, Schema, Keys>, Schema extends StandardSchemaV1 = (Input extends Validator<Name, infer S extends StandardSchemaV1, any> ? S : never), Keys extends keyof RawEventMap = (Input extends Validator<Name, Schema, infer K> ? K : never)>(_: Input, _: Parameters<Input["listen"]>[0]): void;
export declare function useListeners<Name extends string, Map extends ValidatorMap<Name, EventMap, EventTypeKeys>, EventMap extends Record<string, StandardSchemaV1> = (Map extends ValidatorMap<Name, infer EM, any, any> ? EM : never), EventTypeKeys extends keyof RawEventMap = (Map extends ValidatorMap<Name, EventMap, infer K, any> ? K : never)>(_: Map, _: { [K in keyof EventMap]?: ListenerCallback<StandardSchemaV1.InferInput<EventMap[K]>, EventTypeKeys> }): void;
// #endregion