/**
 * Generated by tsnapi — public API snapshot of `@stephansama/eslint-config`
 */
// #region Types
export type BuilderOptions = Partial<{
  autoEnable: boolean;
  overrides: Array<Config>;
  overrides_prepend: Array<Config>;
}>;
export type CommonOptions = Partial<{}>;
export type ConfigDependency = keyof (typeof __json_default_export)["devDependencies"];
export type ConfigOptions = Partial<{ [K in keyof typeof index_d_exports]: boolean | Parameters<(typeof index_d_exports)[K]>[0] }>;
export type Preset = keyof typeof presets_d_exports;
export type StephansamaConfig = keyof typeof index_d_exports;
// #endregion

// #region Functions
export declare function config(_: Options): Promise<Config[]>;
// #endregion

// #region Other
export { index_d_exports as configs }
export { glob_d_exports as globs }
export { presets_d_exports as presets }
// #endregion