/**
 * Generated by tsnapi — public API snapshot of `@stephansama/typed-nocodb-api`
 */
// #region Types
export type ACTION = (typeof ACTIONS)[number];
// #endregion

// #region Functions
export declare function createApi<Schema extends z.ZodObject>({
  baseId,
  origin,
  schema,
  tableId,
  token
}: {
  baseId: string;
  origin: string;
  schema: Schema;
  tableId: string;
  token?: string;
}): {
  fetch<A extends ACTION>(_: ("inputSchema" extends keyof {
    COUNT: {
      method: "get";
      responseSchema: z.ZodUnion<[z.ZodObject<{
        count: z.ZodNumber;
      }, z.core.$strip>, z.ZodObject<{
        msg: z.ZodString;
      }, z.core.$strip>]>;
      url: string;
    };
    CREATE: {
      inputSchema: z.ZodObject<{
        fields: Schema;
      }, z.core.$strip>;
      method: "post";
      responseSchema: z.ZodObject<{
        records: z.ZodArray<z.ZodObject<{
          fields: Schema;
          id: z.ZodString;
        }, z.core.$strip>>;
      }, z.core.$strip>;
      url: string;
    };
    DELETE: {
      inputSchema: z.ZodObject<{
        id: z.ZodNumber;
      }, z.core.$strip>;
      method: "patch";
      responseSchema: z.ZodObject<{}, z.core.$strip>;
      url: string;
    };
    LIST: {
      method: "get";
      querySchema: z.ZodObject<{
        fields: z.ZodOptional<z.ZodUnion<[z.ZodArray<z.ZodString>, z.ZodString]>>;
        limit: z.ZodOptional<z.ZodInt>;
        nestedFields: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnion<[z.ZodArray<z.ZodString>, z.ZodString]>>>;
        offset: z.ZodOptional<z.ZodInt>;
        shuffle: z.ZodOptional<z.ZodBoolean>;
        sort: z.ZodOptional<z.ZodPipe<z.ZodObject<{
          direction: z.ZodEnum<{
            asc: "asc";
            desc: "desc";
          }>;
          field: z.ZodString;
        }, z.core.$strip>, z.ZodTransform<string, {
          direction: "asc" | "desc";
          field: string;
        }>>>;
        viewId: z.ZodOptional<z.ZodString>;
        where: z.ZodOptional<z.ZodString>;
      }, z.core.$strip>;
      responseSchema: z.ZodObject<{
        nestedNext: z.ZodNullable<z.ZodOptional<z.ZodString>>;
        nestedPrev: z.ZodNullable<z.ZodOptional<z.ZodString>>;
        next: z.ZodNullable<z.ZodOptional<z.ZodString>>;
        prev: z.ZodNullable<z.ZodOptional<z.ZodString>>;
        records: z.ZodArray<z.ZodObject<{
          fields: Schema;
          id: z.ZodNumber;
        }, z.core.$strip>>;
      }, z.core.$strip>;
      url: string;
    };
    READ: {
      method: "get";
      responseSchema: z.ZodObject<{
        fields: Schema;
        id: z.ZodNumber;
      }, z.core.$strip>;
      url: string;
    };
    UPDATE: {
      inputSchema: z.ZodObject<{
        fields: Schema;
        id: z.ZodString;
      }, z.core.$strip>;
      method: "patch";
      responseSchema: z.ZodObject<{}, z.core.$strip>;
      url: string;
    };
  }[A] ? {
    body: z.input<{
      COUNT: {
        method: "get";
        responseSchema: z.ZodUnion<[z.ZodObject<{
          count: z.ZodNumber;
        }, z.core.$strip>, z.ZodObject<{
          msg: z.ZodString;
        }, z.core.$strip>]>;
        url: string;
      };
      CREATE: {
        inputSchema: z.ZodObject<{
          fields: Schema;
        }, z.core.$strip>;
        method: "post";
        responseSchema: z.ZodObject<{
          records: z.ZodArray<z.ZodObject<{
            fields: Schema;
            id: z.ZodString;
          }, z.core.$strip>>;
        }, z.core.$strip>;
        url: string;
      };
      DELETE: {
        inputSchema: z.ZodObject<{
          id: z.ZodNumber;
        }, z.core.$strip>;
        method: "patch";
        responseSchema: z.ZodObject<{}, z.core.$strip>;
        url: string;
      };
      LIST: {
        method: "get";
        querySchema: z.ZodObject<{
          fields: z.ZodOptional<z.ZodUnion<[z.ZodArray<z.ZodString>, z.ZodString]>>;
          limit: z.ZodOptional<z.ZodInt>;
          nestedFields: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnion<[z.ZodArray<z.ZodString>, z.ZodString]>>>;
          offset: z.ZodOptional<z.ZodInt>;
          shuffle: z.ZodOptional<z.ZodBoolean>;
          sort: z.ZodOptional<z.ZodPipe<z.ZodObject<{
            direction: z.ZodEnum<{
              asc: "asc";
              desc: "desc";
            }>;
            field: z.ZodString;
          }, z.core.$strip>, z.ZodTransform<string, {
            direction: "asc" | "desc";
            field: string;
          }>>>;
          viewId: z.ZodOptional<z.ZodString>;
          where: z.ZodOptional<z.ZodString>;
        }, z.core.$strip>;
        responseSchema: z.ZodObject<{
          nestedNext: z.ZodNullable<z.ZodOptional<z.ZodString>>;
          nestedPrev: z.ZodNullable<z.ZodOptional<z.ZodString>>;
          next: z.ZodNullable<z.ZodOptional<z.ZodString>>;
          prev: z.ZodNullable<z.ZodOptional<z.ZodString>>;
          records: z.ZodArray<z.ZodObject<{
            fields: Schema;
            id: z.ZodNumber;
          }, z.core.$strip>>;
        }, z.core.$strip>;
        url: string;
      };
      READ: {
        method: "get";
        responseSchema: z.ZodObject<{
          fields: Schema;
          id: z.ZodNumber;
        }, z.core.$strip>;
        url: string;
      };
      UPDATE: {
        inputSchema: z.ZodObject<{
          fields: Schema;
          id: z.ZodString;
        }, z.core.$strip>;
        method: "patch";
        responseSchema: z.ZodObject<{}, z.core.$strip>;
        url: string;
      };
    }[A]["inputSchema"]>;
  } : {}) & ("querySchema" extends keyof {
    COUNT: {
      method: "get";
      responseSchema: z.ZodUnion<[z.ZodObject<{
        count: z.ZodNumber;
      }, z.core.$strip>, z.ZodObject<{
        msg: z.ZodString;
      }, z.core.$strip>]>;
      url: string;
    };
    CREATE: {
      inputSchema: z.ZodObject<{
        fields: Schema;
      }, z.core.$strip>;
      method: "post";
      responseSchema: z.ZodObject<{
        records: z.ZodArray<z.ZodObject<{
          fields: Schema;
          id: z.ZodString;
        }, z.core.$strip>>;
      }, z.core.$strip>;
      url: string;
    };
    DELETE: {
      inputSchema: z.ZodObject<{
        id: z.ZodNumber;
      }, z.core.$strip>;
      method: "patch";
      responseSchema: z.ZodObject<{}, z.core.$strip>;
      url: string;
    };
    LIST: {
      method: "get";
      querySchema: z.ZodObject<{
        fields: z.ZodOptional<z.ZodUnion<[z.ZodArray<z.ZodString>, z.ZodString]>>;
        limit: z.ZodOptional<z.ZodInt>;
        nestedFields: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnion<[z.ZodArray<z.ZodString>, z.ZodString]>>>;
        offset: z.ZodOptional<z.ZodInt>;
        shuffle: z.ZodOptional<z.ZodBoolean>;
        sort: z.ZodOptional<z.ZodPipe<z.ZodObject<{
          direction: z.ZodEnum<{
            asc: "asc";
            desc: "desc";
          }>;
          field: z.ZodString;
        }, z.core.$strip>, z.ZodTransform<string, {
          direction: "asc" | "desc";
          field: string;
        }>>>;
        viewId: z.ZodOptional<z.ZodString>;
        where: z.ZodOptional<z.ZodString>;
      }, z.core.$strip>;
      responseSchema: z.ZodObject<{
        nestedNext: z.ZodNullable<z.ZodOptional<z.ZodString>>;
        nestedPrev: z.ZodNullable<z.ZodOptional<z.ZodString>>;
        next: z.ZodNullable<z.ZodOptional<z.ZodString>>;
        prev: z.ZodNullable<z.ZodOptional<z.ZodString>>;
        records: z.ZodArray<z.ZodObject<{
          fields: Schema;
          id: z.ZodNumber;
        }, z.core.$strip>>;
      }, z.core.$strip>;
      url: string;
    };
    READ: {
      method: "get";
      responseSchema: z.ZodObject<{
        fields: Schema;
        id: z.ZodNumber;
      }, z.core.$strip>;
      url: string;
    };
    UPDATE: {
      inputSchema: z.ZodObject<{
        fields: Schema;
        id: z.ZodString;
      }, z.core.$strip>;
      method: "patch";
      responseSchema: z.ZodObject<{}, z.core.$strip>;
      url: string;
    };
  }[A] ? {
    query?: z.input<{
      COUNT: {
        method: "get";
        responseSchema: z.ZodUnion<[z.ZodObject<{
          count: z.ZodNumber;
        }, z.core.$strip>, z.ZodObject<{
          msg: z.ZodString;
        }, z.core.$strip>]>;
        url: string;
      };
      CREATE: {
        inputSchema: z.ZodObject<{
          fields: Schema;
        }, z.core.$strip>;
        method: "post";
        responseSchema: z.ZodObject<{
          records: z.ZodArray<z.ZodObject<{
            fields: Schema;
            id: z.ZodString;
          }, z.core.$strip>>;
        }, z.core.$strip>;
        url: string;
      };
      DELETE: {
        inputSchema: z.ZodObject<{
          id: z.ZodNumber;
        }, z.core.$strip>;
        method: "patch";
        responseSchema: z.ZodObject<{}, z.core.$strip>;
        url: string;
      };
      LIST: {
        method: "get";
        querySchema: z.ZodObject<{
          fields: z.ZodOptional<z.ZodUnion<[z.ZodArray<z.ZodString>, z.ZodString]>>;
          limit: z.ZodOptional<z.ZodInt>;
          nestedFields: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnion<[z.ZodArray<z.ZodString>, z.ZodString]>>>;
          offset: z.ZodOptional<z.ZodInt>;
          shuffle: z.ZodOptional<z.ZodBoolean>;
          sort: z.ZodOptional<z.ZodPipe<z.ZodObject<{
            direction: z.ZodEnum<{
              asc: "asc";
              desc: "desc";
            }>;
            field: z.ZodString;
          }, z.core.$strip>, z.ZodTransform<string, {
            direction: "asc" | "desc";
            field: string;
          }>>>;
          viewId: z.ZodOptional<z.ZodString>;
          where: z.ZodOptional<z.ZodString>;
        }, z.core.$strip>;
        responseSchema: z.ZodObject<{
          nestedNext: z.ZodNullable<z.ZodOptional<z.ZodString>>;
          nestedPrev: z.ZodNullable<z.ZodOptional<z.ZodString>>;
          next: z.ZodNullable<z.ZodOptional<z.ZodString>>;
          prev: z.ZodNullable<z.ZodOptional<z.ZodString>>;
          records: z.ZodArray<z.ZodObject<{
            fields: Schema;
            id: z.ZodNumber;
          }, z.core.$strip>>;
        }, z.core.$strip>;
        url: string;
      };
      READ: {
        method: "get";
        responseSchema: z.ZodObject<{
          fields: Schema;
          id: z.ZodNumber;
        }, z.core.$strip>;
        url: string;
      };
      UPDATE: {
        inputSchema: z.ZodObject<{
          fields: Schema;
          id: z.ZodString;
        }, z.core.$strip>;
        method: "patch";
        responseSchema: z.ZodObject<{}, z.core.$strip>;
        url: string;
      };
    }[A]["querySchema"]>;
  } : {}) & {
    action: A;
    token?: string;
  }): Promise<z.core.output<{
    COUNT: {
      method: "get";
      responseSchema: z.ZodUnion<[z.ZodObject<{
        count: z.ZodNumber;
      }, z.core.$strip>, z.ZodObject<{
        msg: z.ZodString;
      }, z.core.$strip>]>;
      url: string;
    };
    CREATE: {
      inputSchema: z.ZodObject<{
        fields: Schema;
      }, z.core.$strip>;
      method: "post";
      responseSchema: z.ZodObject<{
        records: z.ZodArray<z.ZodObject<{
          fields: Schema;
          id: z.ZodString;
        }, z.core.$strip>>;
      }, z.core.$strip>;
      url: string;
    };
    DELETE: {
      inputSchema: z.ZodObject<{
        id: z.ZodNumber;
      }, z.core.$strip>;
      method: "patch";
      responseSchema: z.ZodObject<{}, z.core.$strip>;
      url: string;
    };
    LIST: {
      method: "get";
      querySchema: z.ZodObject<{
        fields: z.ZodOptional<z.ZodUnion<[z.ZodArray<z.ZodString>, z.ZodString]>>;
        limit: z.ZodOptional<z.ZodInt>;
        nestedFields: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnion<[z.ZodArray<z.ZodString>, z.ZodString]>>>;
        offset: z.ZodOptional<z.ZodInt>;
        shuffle: z.ZodOptional<z.ZodBoolean>;
        sort: z.ZodOptional<z.ZodPipe<z.ZodObject<{
          direction: z.ZodEnum<{
            asc: "asc";
            desc: "desc";
          }>;
          field: z.ZodString;
        }, z.core.$strip>, z.ZodTransform<string, {
          direction: "asc" | "desc";
          field: string;
        }>>>;
        viewId: z.ZodOptional<z.ZodString>;
        where: z.ZodOptional<z.ZodString>;
      }, z.core.$strip>;
      responseSchema: z.ZodObject<{
        nestedNext: z.ZodNullable<z.ZodOptional<z.ZodString>>;
        nestedPrev: z.ZodNullable<z.ZodOptional<z.ZodString>>;
        next: z.ZodNullable<z.ZodOptional<z.ZodString>>;
        prev: z.ZodNullable<z.ZodOptional<z.ZodString>>;
        records: z.ZodArray<z.ZodObject<{
          fields: Schema;
          id: z.ZodNumber;
        }, z.core.$strip>>;
      }, z.core.$strip>;
      url: string;
    };
    READ: {
      method: "get";
      responseSchema: z.ZodObject<{
        fields: Schema;
        id: z.ZodNumber;
      }, z.core.$strip>;
      url: string;
    };
    UPDATE: {
      inputSchema: z.ZodObject<{
        fields: Schema;
        id: z.ZodString;
      }, z.core.$strip>;
      method: "patch";
      responseSchema: z.ZodObject<{}, z.core.$strip>;
      url: string;
    };
  }[A]["responseSchema"]>>;
};
// #endregion

// #region Variables
export declare const ACTIONS: readonly ["LIST", "CREATE", "UPDATE", "DELETE", "READ", "COUNT"];
// #endregion