/**
 * Generated by tsnapi — public API snapshot of `@stephansama/monorule/cli`
 */
// #region Functions
export declare function run(): Promise<void>;
// #endregion

// #region Variables
export declare const arguments_: ({
  command: undefined;
  flags: {
    dryRun: boolean;
    verbose: number;
    ignorePaths: string[] | readonly [];
    ignoreRules: string[] | readonly [];
    ruleDirectory: string;
    config: string;
    version: boolean | undefined;
    help: boolean | undefined;
  };
  unknownFlags: {
    [flagName: string]: (string | boolean)[];
  };
  _: string[] & {
    "--": string[];
  } & {};
  showHelp: (options?: {
    version?: string;
    description?: string;
    usage?: false | string | string[];
    examples?: string | string[];
    render?: (nodes: {
      id?: string;
      type: keyof Renderers;
      data: any;
    }[], renderers: Renderers) => string;
  }) => void;
  showVersion: () => void;
} | {
  command: "generate";
  flags: {
    help: boolean | undefined;
  };
  unknownFlags: {
    [flagName: string]: (string | boolean)[];
  };
  _: string[] & {
    "--": string[];
  } & {};
  showHelp: (options?: {
    version?: string;
    description?: string;
    usage?: false | string | string[];
    examples?: string | string[];
    render?: (nodes: {
      id?: string;
      type: keyof Renderers;
      data: any;
    }[], renderers: Renderers) => string;
  }) => void;
  showVersion: () => void;
}) & Promise<void>;
export declare const baseFlags: {
  readonly config: {
    readonly alias: "c";
    readonly default: "";
    readonly description: "location of configuration to use";
    readonly type: StringConstructor;
  };
};
export declare const configFlags: {
  readonly ignorePaths: {
    readonly default: readonly [];
    readonly description: "list of files to ignore";
    readonly type: readonly [StringConstructor];
  };
  readonly ignoreRules: {
    readonly default: readonly [];
    readonly description: "list of rules to ignore";
    readonly type: readonly [StringConstructor];
  };
  readonly ruleDirectory: {
    readonly default: "rules";
    readonly description: "rules directory";
    readonly type: StringConstructor;
  };
};
// #endregion