/**
 * Generated by tsnapi — public API snapshot of `@stephansama/monorule`
 */
// #region Types
export type ConfigSchema = output<typeof configSchema>;
export type DefaultRuleParseType = "json" | "toml" | "txt" | "yaml";
export type DirtyFile<T = unknown> = {
  absolutePath: string;
  content: T;
  raw: string;
  relativePath: string;
  rule: string;
};
export type FullConfigSchema = output<typeof fullConfigSchema>;
export type RuleBase<T, Context = DirtyFile> = {
  apply?: ((_: NoInfer<T>) => Promise<T>) | ((_: NoInfer<T>) => T);
  context?(_: string): Context;
  enabled?: boolean;
  name: string;
  pattern: string;
  when(_: NoInfer<T>): boolean;
};
export type UserConfig<Rules extends Rule[]> = Omit<FullConfigSchema, "rules"> & {
  rules: Rules;
};
// #endregion

// #region Functions
export declare function defineConfig<Rules extends Rule[]>(_: UserConfig<Rules>): UserConfig<Rules>;
export declare function defineRule<const Parse extends DefaultRuleParseType, Context = DirtyFile>(_: DefaultParserRule<Parse, DefaultRuleParseTypeExtract<Parse>, Context>): DefaultParserRule<Parse, DefaultRuleParseTypeExtract<Parse>, Context>;
// #endregion

// #region Variables
export declare const configSchema: ZodObject<{
  ignorePaths: ZodDefault<ZodArray<ZodString>>;
  ignoreRules: ZodDefault<ZodArray<ZodString>>;
  ruleDirectory: ZodDefault<ZodString>;
}, $strip>;
export declare const fullConfigSchema: ZodObject<{
  ignorePaths: ZodDefault<ZodArray<ZodString>>;
  ignoreRules: ZodDefault<ZodArray<ZodString>>;
  ruleDirectory: ZodDefault<ZodString>;
  rules: ZodDefault<ZodArray<ZodObject<{
    apply: ZodFunction<$ZodFunctionArgs, $ZodFunctionOut>;
    name: ZodString;
    parse: ZodUnion<[ZodFunction<$ZodFunctionArgs, $ZodFunctionOut>, ZodEnum<{
      json: "json";
      txt: "txt";
      yaml: "yaml";
      toml: "toml";
    }>]>;
    pattern: ZodString;
    when: ZodFunction<$ZodFunctionArgs, $ZodFunctionOut>;
  }, $strip>>>;
}, $strip>;
// #endregion