/**
 * Generated by tsnapi — public API snapshot of `@stephansama/monorule`
 */
// #region Types
export type BuiltinParseEnumSchema = output<typeof builtinParseEnumSchema>;
export type ConfigSchema = output<typeof configSchema>;
export type DirtyFile<T = unknown> = LocationContext & {
  closestPackage: Undefinable<PackageContext>;
  content: T;
  packages: Array<PackageContext>;
  raw: string;
  rootPackage: Omit<PackageContext, "relativePath">;
  rule: string;
};
export type Error<T extends string = string> = {
  fixable?: boolean;
  id: T;
  message: string;
};
export type FullConfigSchema = output<typeof fullConfigSchema>;
export type RuleBase<T, Context = DirtyFile> = {
  apply?: (_: NoInfer<T>, _?: Context) => Promise<T> | T;
  enabled?: boolean;
  exclude?: string | string[];
  include: string | string[];
  name: string;
  when(_: NoInfer<T>, _?: Context): Array<Error> | void;
};
export type UserConfig<T> = Omit<FullConfigSchema, "rules"> & {
  rules: T;
};
// #endregion

// #region Functions
export declare function defineConfig<T>(_: UserConfig<T>): UserConfig<T>;
export declare function defineRule<const Parse extends BuiltinParseEnumSchema, Context = DirtyFile>(_: DefaultParserRule<Parse, DefaultRuleParseTypeExtract<Parse>, Context>): DefaultParserRule<Parse, DefaultRuleParseTypeExtract<Parse>, Context>;
export declare function loadRules(_: ConfigSchema, _?: string): Promise<{
  enabled: boolean;
  include: string | string[];
  name: string;
  parse: "json" | "txt" | "yaml" | "toml" | $InferOuterFunctionType<$ZodFunctionArgs, $ZodFunctionOut>;
  when: $InferOuterFunctionType<$ZodFunctionArgs, $ZodFunctionOut>;
  apply?: $InferOuterFunctionType<$ZodFunctionArgs, $ZodFunctionOut> | undefined;
  exclude?: string | string[] | undefined;
}[]>;
export declare function parse<T>(_: string, _: BuiltinParseEnumSchema | FunctionParserRule<T>["parse"]): T;
export declare function stringify(_: unknown, _: BuiltinParseEnumSchema): string;
// #endregion

// #region Variables
export declare const configSchema: ZodObject<{
  ignorePaths: ZodDefault<ZodArray<ZodString>>;
  ignoreRules: ZodDefault<ZodArray<ZodString>>;
  ruleDirectory: ZodDefault<ZodString>;
}, $strip>;
export declare const DEFAULT_IGNORE_LIST: readonly ["**/.astro/**", "**/.next/**", "**/.nuxt/**", "**/.output/**", "**/.svelte-kit/**", "**/.svelte/**", "**/dist/**", "**/node_modules/**"];
export declare const fullConfigSchema: ZodObject<{
  ignorePaths: ZodDefault<ZodArray<ZodString>>;
  ignoreRules: ZodDefault<ZodArray<ZodString>>;
  ruleDirectory: ZodDefault<ZodString>;
  rules: ZodDefault<ZodArray<ZodObject<{
    apply: ZodOptional<ZodFunction<$ZodFunctionArgs, $ZodFunctionOut>>;
    enabled: ZodDefault<ZodBoolean>;
    exclude: ZodOptional<ZodUnion<[ZodArray<ZodString>, ZodString]>>;
    include: ZodUnion<readonly [ZodArray<ZodString>, ZodString]>;
    name: ZodString;
    parse: ZodUnion<[ZodFunction<$ZodFunctionArgs, $ZodFunctionOut>, ZodEnum<{
      json: "json";
      txt: "txt";
      yaml: "yaml";
      toml: "toml";
    }>]>;
    when: ZodFunction<$ZodFunctionArgs, $ZodFunctionOut>;
  }, $strip>>>;
}, $strip>;
export declare const parsers: {
  readonly json: (text: string, reviver?: (this: any, key: string, value: any) => any) => any;
  readonly toml: typeof toml.parse;
  readonly txt: (input: string) => string;
  readonly yaml: typeof yaml.parse;
};
export declare const stringifiers: {
  readonly json: {
    (value: any, replacer?: (this: any, key: string, value: any) => any, space?: string | number): string;
    (value: any, replacer?: (number | string)[] | null, space?: string | number): string;
  };
  readonly toml: typeof toml.stringify;
  readonly txt: (input: unknown) => string;
  readonly yaml: typeof yaml.stringify;
};
// #endregion