/**
 * Generated by tsnapi — public API snapshot of `@stephansama/monorule/schema`
 */
// #region Types
export type BuiltinParseEnumSchema = output<typeof builtinParseEnumSchema>;
export type ConfigSchema = output<typeof configSchema>;
export type FullConfigSchema = output<typeof fullConfigSchema>;
export type RuleMapSchema = output<typeof ruleMapSchema>;
export type RuleSchema = output<typeof ruleSchema>;
// #endregion

// #region Variables
export declare const builtinParseEnumSchema: ZodEnum<{
  json: "json";
  txt: "txt";
  yaml: "yaml";
  toml: "toml";
}>;
export declare const configSchema: ZodObject<{
  ignorePaths: ZodDefault<ZodArray<ZodString>>;
  ignoreRules: ZodDefault<ZodArray<ZodString>>;
  ruleDirectory: ZodDefault<ZodString>;
}, $strip>;
export declare const fullConfigSchema: ZodObject<{
  ignorePaths: ZodDefault<ZodArray<ZodString>>;
  ignoreRules: ZodDefault<ZodArray<ZodString>>;
  ruleDirectory: ZodDefault<ZodString>;
  rules: ZodDefault<ZodArray<ZodObject<{
    apply: ZodOptional<ZodFunction<$ZodFunctionArgs, $ZodFunctionOut>>;
    enabled: ZodDefault<ZodBoolean>;
    errors: ZodDefault<ZodRecord<ZodString, ZodUnknown>>;
    exclude: ZodOptional<ZodUnion<[ZodArray<ZodString>, ZodString]>>;
    include: ZodUnion<readonly [ZodArray<ZodString>, ZodString]>;
    name: ZodString;
    parse: ZodUnion<[ZodFunction<$ZodFunctionArgs, $ZodFunctionOut>, ZodEnum<{
      json: "json";
      txt: "txt";
      yaml: "yaml";
      toml: "toml";
    }>]>;
    stringify: ZodOptional<ZodFunction<$ZodFunctionArgs, $ZodFunctionOut>>;
    when: ZodFunction<$ZodFunctionArgs, $ZodFunctionOut>;
  }, $loose>>>;
}, $strip>;
export declare const ruleMapSchema: ZodRecord<ZodString, ZodObject<{
  apply: ZodOptional<ZodFunction<$ZodFunctionArgs, $ZodFunctionOut>>;
  enabled: ZodDefault<ZodBoolean>;
  errors: ZodDefault<ZodRecord<ZodString, ZodUnknown>>;
  exclude: ZodOptional<ZodUnion<[ZodArray<ZodString>, ZodString]>>;
  include: ZodUnion<readonly [ZodArray<ZodString>, ZodString]>;
  name: ZodString;
  parse: ZodUnion<[ZodFunction<$ZodFunctionArgs, $ZodFunctionOut>, ZodEnum<{
    json: "json";
    txt: "txt";
    yaml: "yaml";
    toml: "toml";
  }>]>;
  stringify: ZodOptional<ZodFunction<$ZodFunctionArgs, $ZodFunctionOut>>;
  when: ZodFunction<$ZodFunctionArgs, $ZodFunctionOut>;
}, $loose>>;
export declare const ruleSchema: ZodObject<{
  apply: ZodOptional<ZodFunction<$ZodFunctionArgs, $ZodFunctionOut>>;
  enabled: ZodDefault<ZodBoolean>;
  errors: ZodDefault<ZodRecord<ZodString, ZodUnknown>>;
  exclude: ZodOptional<ZodUnion<[ZodArray<ZodString>, ZodString]>>;
  include: ZodUnion<readonly [ZodArray<ZodString>, ZodString]>;
  name: ZodString;
  parse: ZodUnion<[ZodFunction<$ZodFunctionArgs, $ZodFunctionOut>, ZodEnum<{
    json: "json";
    txt: "txt";
    yaml: "yaml";
    toml: "toml";
  }>]>;
  stringify: ZodOptional<ZodFunction<$ZodFunctionArgs, $ZodFunctionOut>>;
  when: ZodFunction<$ZodFunctionArgs, $ZodFunctionOut>;
}, $loose>;
// #endregion