/**
 * Generated by tsnapi — public API snapshot of `@stephansama/monorule/schema`
 */
// #region Types
export type ConfigSchema = output<typeof configSchema>;
export type FullConfigSchema = output<typeof fullConfigSchema>;
// #endregion

// #region Variables
export declare const configSchema: ZodObject<{
  ignorePaths: ZodDefault<ZodArray<ZodString>>;
  ignoreRules: ZodDefault<ZodArray<ZodString>>;
  ruleDirectory: ZodDefault<ZodString>;
}, $strip>;
export declare const fullConfigSchema: ZodObject<{
  ignorePaths: ZodDefault<ZodArray<ZodString>>;
  ignoreRules: ZodDefault<ZodArray<ZodString>>;
  ruleDirectory: ZodDefault<ZodString>;
  rules: ZodDefault<ZodArray<ZodObject<{
    apply: ZodFunction<$ZodFunctionArgs, $ZodFunctionOut>;
    name: ZodString;
    parse: ZodUnion<[ZodFunction<$ZodFunctionArgs, $ZodFunctionOut>, ZodEnum<{
      json: "json";
      txt: "txt";
      yaml: "yaml";
      toml: "toml";
    }>]>;
    pattern: ZodString;
    when: ZodFunction<$ZodFunctionArgs, $ZodFunctionOut>;
  }, $strip>>>;
}, $strip>;
// #endregion