/**
 * Generated by tsnapi — public API snapshot of `@stephansama/monorule/schema`
 */
// #region Types
export type BuiltinParseEnumSchema = output<typeof builtinParseEnumSchema>;
export type ConfigSchema = output<typeof configSchema>;
export type DirtyFileBase = output<typeof dirtyFileBaseSchema>;
export type ErrorValue = output<typeof errorValueSchema>;
export type FullConfigSchema = output<typeof fullConfigSchema>;
export type LocationContext = output<typeof locationContextSchema>;
export type PackageContext = output<typeof packageContextSchema>;
export type PackageJsonContext = output<typeof packageJsonContextSchema>;
export type RuleError = output<typeof errorSchema>;
export type RuleMapSchema = output<typeof ruleMapSchema>;
export type RuleSchema = input<typeof ruleSchema>;
export type Undefinable<T extends object> = { [k in keyof T]: T[k] | undefined };
// #endregion

// #region Variables
export declare const builtinParseEnumSchema: ZodEnum<{
  json: "json";
  txt: "txt";
  yaml: "yaml";
  toml: "toml";
}>;
export declare const configSchema: ZodObject<{
  ignorePaths: ZodDefault<ZodArray<ZodString>>;
  ignoreRules: ZodDefault<ZodArray<ZodString>>;
  ruleDirectory: ZodDefault<ZodString>;
}, $strip>;
export declare const dirtyFileBaseSchema: ZodObject<{
  absolutePath: ZodString;
  relativePath: ZodString;
  closestPackage: ZodCustom<Undefinable<{
    absolutePath: string;
    relativePath: string;
    json: PackageJSON;
  }>, Undefinable<{
    absolutePath: string;
    relativePath: string;
    json: PackageJSON;
  }>>;
  content: ZodUnknown;
  packages: ZodArray<ZodObject<{
    absolutePath: ZodString;
    relativePath: ZodString;
    json: ZodCustom<PackageJSON, PackageJSON>;
  }, $strip>>;
  raw: ZodString;
  rootPackage: ZodObject<{
    json: ZodCustom<PackageJSON, PackageJSON>;
    absolutePath: ZodString;
  }, $strip>;
  rule: ZodString;
}, $strip>;
export declare const errorSchema: ZodObject<{
  fixable: ZodOptional<ZodBoolean>;
  id: ZodString;
  message: ZodString;
}, $strip>;
export declare const errorValueSchema: ZodUnion<readonly [ZodString, ZodObject<{
  fixable: ZodOptional<ZodBoolean>;
  message: ZodString;
}, $strip>]>;
export declare const fullConfigSchema: ZodObject<{
  ignorePaths: ZodDefault<ZodArray<ZodString>>;
  ignoreRules: ZodDefault<ZodArray<ZodString>>;
  ruleDirectory: ZodDefault<ZodString>;
  rules: ZodDefault<ZodArray<ZodObject<{
    apply: ZodOptional<ZodCustom<ApplyFunction, ApplyFunction>>;
    enabled: ZodDefault<ZodBoolean>;
    errors: ZodDefault<ZodRecord<ZodString, ZodUnion<readonly [ZodString, ZodObject<{
      fixable: ZodOptional<ZodBoolean>;
      message: ZodString;
    }, $strip>]>>>;
    exclude: ZodOptional<ZodUnion<[ZodArray<ZodString>, ZodString]>>;
    include: ZodUnion<readonly [ZodArray<ZodString>, ZodString]>;
    name: ZodString;
    parse: ZodUnion<readonly [ZodCustom<ParseFunction, ParseFunction>, ZodEnum<{
      json: "json";
      txt: "txt";
      yaml: "yaml";
      toml: "toml";
    }>]>;
    stringify: ZodOptional<ZodCustom<StringifyFunction, StringifyFunction>>;
    when: ZodCustom<WhenFunction, WhenFunction>;
  }, $strip>>>;
}, $strip>;
export declare const locationContextSchema: ZodObject<{
  absolutePath: ZodString;
  relativePath: ZodString;
}, $strip>;
export declare const packageContextSchema: ZodObject<{
  absolutePath: ZodString;
  relativePath: ZodString;
  json: ZodCustom<PackageJSON, PackageJSON>;
}, $strip>;
export declare const packageJsonContextSchema: ZodObject<{
  json: ZodCustom<PackageJSON, PackageJSON>;
}, $strip>;
export declare const ruleMapSchema: ZodRecord<ZodString, ZodObject<{
  apply: ZodOptional<ZodCustom<ApplyFunction, ApplyFunction>>;
  enabled: ZodDefault<ZodBoolean>;
  errors: ZodDefault<ZodRecord<ZodString, ZodUnion<readonly [ZodString, ZodObject<{
    fixable: ZodOptional<ZodBoolean>;
    message: ZodString;
  }, $strip>]>>>;
  exclude: ZodOptional<ZodUnion<[ZodArray<ZodString>, ZodString]>>;
  include: ZodUnion<readonly [ZodArray<ZodString>, ZodString]>;
  name: ZodString;
  parse: ZodUnion<readonly [ZodCustom<ParseFunction, ParseFunction>, ZodEnum<{
    json: "json";
    txt: "txt";
    yaml: "yaml";
    toml: "toml";
  }>]>;
  stringify: ZodOptional<ZodCustom<StringifyFunction, StringifyFunction>>;
  when: ZodCustom<WhenFunction, WhenFunction>;
}, $strip>>;
export declare const ruleSchema: ZodObject<{
  apply: ZodOptional<ZodCustom<ApplyFunction, ApplyFunction>>;
  enabled: ZodDefault<ZodBoolean>;
  errors: ZodDefault<ZodRecord<ZodString, ZodUnion<readonly [ZodString, ZodObject<{
    fixable: ZodOptional<ZodBoolean>;
    message: ZodString;
  }, $strip>]>>>;
  exclude: ZodOptional<ZodUnion<[ZodArray<ZodString>, ZodString]>>;
  include: ZodUnion<readonly [ZodArray<ZodString>, ZodString]>;
  name: ZodString;
  parse: ZodUnion<readonly [ZodCustom<ParseFunction, ParseFunction>, ZodEnum<{
    json: "json";
    txt: "txt";
    yaml: "yaml";
    toml: "toml";
  }>]>;
  stringify: ZodOptional<ZodCustom<StringifyFunction, StringifyFunction>>;
  when: ZodCustom<WhenFunction, WhenFunction>;
}, $strip>;
// #endregion