/**
 * Generated by tsnapi — public API snapshot of `@stephansama/pnpm-hooks/types`
 */
// #region Types
export type AfterAllResolvedHook = (_: LockfileObject, _: HookContext) => LockfileObject | Promise<LockfileObject>;
export type BeforePackingHook<PackageJson extends BaseManifest = BaseManifest> = (_: PackageJson) => PackageJson | Promise<PackageJson>;
export type ImportPackageHook = (_: string, _: ImportPackageOptions) => Promise<string | undefined>;
export type ImportPackageOptions = Partial<{
  disableRelinkLocalDirDeps: boolean;
  filesMap: Record<string, string>;
  force: boolean;
  keepModulesDir: boolean;
  resolvedFrom: string;
}>;
export type PnpmFileHooks = Partial<{
  afterAllResolved: AfterAllResolvedHook;
  beforePacking: BeforePackingHook;
  fetchers: unknown;
  importPackage: ImportPackageHook;
  preResolution: PreResolutionHook;
  readPackage: ReadPackageHook;
  updateConfig: UpdateConfigHook;
}>;
export type PnpmFinder = (_: PnpmFinderContext) => boolean;
export type PnpmFinderContext = {
  name: string;
  readManifest(): BaseManifest;
  version: string;
};
export type PnpmFinders = Record<string, PnpmFinder>;
export type PreResolutionHook = (_: PreResolutionOptions) => Promise<void>;
export type PreResolutionOptions = Partial<{
  currentLockfile: string;
  existsCurrentLockfile: boolean;
  existsNonEmptyWantedLockfile: boolean;
  lockfileDir: string;
  registries: Record<string, string>;
  storeDir: string;
  wantedLockfile: string;
}>;
export type ReadPackageHook = <PackageJson extends BaseManifest>(_: PackageJson, _: HookContext) => PackageJson | Promise<PackageJson>;
export type UpdateConfigHook = <Config extends Record<string, string>>(_: Config) => Config | Promise<Config>;
// #endregion

// #region Other
export { types_d_exports as t }
// #endregion