/**
 * Generated by tsnapi — public API snapshot of `@stephansama/types-lhci`
 */
// #region Types
export type LhciAssertSchema = z.infer<typeof lhciAssertSchema>;
export type LhciBasicAuthSchema = z.infer<typeof lhciBasicAuthSchema>;
export type LhciCollectSchema = z.infer<typeof lhciCollectSchema>;
export type LhciSchema = z.infer<typeof lhciSchema>;
export type LhciServerSchema = z.infer<typeof lhciServerSchema>;
export type LhciUploadSchema = z.infer<typeof lhciUploadSchema>;
export type LhciWizardSchema = z.infer<typeof lhciWizardSchema>;
// #endregion

// #region Variables
export declare const lhciAssertSchema: z.ZodObject<{
  assertions: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnion<[z.ZodTuple<[z.ZodEnum<{
    warn: "warn";
    error: "error";
  }>, z.ZodObject<{
    maxLength: z.ZodNumber;
    minScore: z.ZodNumber;
  }, z.core.$strip>], null>, z.ZodEnum<{
    off: "off";
  }>]>>>;
  budgetsFile: z.ZodOptional<z.ZodString>;
  includePassedAssertions: z.ZodOptional<z.ZodBoolean>;
  preset: z.ZodOptional<z.ZodEnum<{
    "lighthouse:all": "lighthouse:all";
    "lighthouse:recommended": "lighthouse:recommended";
    "lighthouse:no-pwa": "lighthouse:no-pwa";
  }>>;
}, z.core.$strip>;
export declare const lhciBasicAuthSchema: z.ZodObject<{
  password: z.ZodString;
  username: z.ZodString;
}, z.core.$strip>;
export declare const lhciCollectSchema: z.ZodObject<{
  additive: z.ZodOptional<z.ZodBoolean>;
  autodiscoverUrlBlocklist: z.ZodOptional<z.ZodArray<z.ZodString>>;
  chromePath: z.ZodOptional<z.ZodString>;
  headful: z.ZodOptional<z.ZodBoolean>;
  isSinglePageApplication: z.ZodOptional<z.ZodBoolean>;
  method: z.ZodDefault<z.ZodUnion<[z.ZodEnum<{
    node: "node";
    psi: "psi";
  }>, z.ZodString]>>;
  numberOfRuns: z.ZodOptional<z.ZodNumber>;
  puppeteerLaunchOptions: z.ZodObject<{
    devtools: z.ZodBoolean;
    handleSIGHUP: z.ZodDefault<z.ZodBoolean>;
    handleSIGINT: z.ZodDefault<z.ZodBoolean>;
    handleSIGTERM: z.ZodDefault<z.ZodBoolean>;
    pipe: z.ZodDefault<z.ZodBoolean>;
    timeout: z.ZodDefault<z.ZodNumber>;
  }, z.core.$strip>;
  puppeteerScript: z.ZodOptional<z.ZodString>;
  settings: z.ZodObject<{}, z.core.$strip>;
  startServerCommand: z.ZodOptional<z.ZodString>;
  startServerReadyPattern: z.ZodDefault<z.ZodString>;
  startServerReadyTimeout: z.ZodDefault<z.ZodNumber>;
  staticDirFileDiscoveryDepth: z.ZodDefault<z.ZodNumber>;
  staticDistDir: z.ZodOptional<z.ZodString>;
  url: z.ZodOptional<z.ZodArray<z.ZodString>>;
}, z.core.$strip>;
export declare const lhciSchema: z.ZodObject<{
  ci: z.ZodObject<{
    assert: z.ZodOptional<z.ZodObject<{
      assertions: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnion<[z.ZodTuple<[z.ZodEnum<{
        warn: "warn";
        error: "error";
      }>, z.ZodObject<{
        maxLength: z.ZodNumber;
        minScore: z.ZodNumber;
      }, z.core.$strip>], null>, z.ZodEnum<{
        off: "off";
      }>]>>>;
      budgetsFile: z.ZodOptional<z.ZodString>;
      includePassedAssertions: z.ZodOptional<z.ZodBoolean>;
      preset: z.ZodOptional<z.ZodEnum<{
        "lighthouse:all": "lighthouse:all";
        "lighthouse:recommended": "lighthouse:recommended";
        "lighthouse:no-pwa": "lighthouse:no-pwa";
      }>>;
    }, z.core.$strip>>;
    collect: z.ZodOptional<z.ZodObject<{
      additive: z.ZodOptional<z.ZodBoolean>;
      autodiscoverUrlBlocklist: z.ZodOptional<z.ZodArray<z.ZodString>>;
      chromePath: z.ZodOptional<z.ZodString>;
      headful: z.ZodOptional<z.ZodBoolean>;
      isSinglePageApplication: z.ZodOptional<z.ZodBoolean>;
      method: z.ZodDefault<z.ZodUnion<[z.ZodEnum<{
        node: "node";
        psi: "psi";
      }>, z.ZodString]>>;
      numberOfRuns: z.ZodOptional<z.ZodNumber>;
      puppeteerLaunchOptions: z.ZodObject<{
        devtools: z.ZodBoolean;
        handleSIGHUP: z.ZodDefault<z.ZodBoolean>;
        handleSIGINT: z.ZodDefault<z.ZodBoolean>;
        handleSIGTERM: z.ZodDefault<z.ZodBoolean>;
        pipe: z.ZodDefault<z.ZodBoolean>;
        timeout: z.ZodDefault<z.ZodNumber>;
      }, z.core.$strip>;
      puppeteerScript: z.ZodOptional<z.ZodString>;
      settings: z.ZodObject<{}, z.core.$strip>;
      startServerCommand: z.ZodOptional<z.ZodString>;
      startServerReadyPattern: z.ZodDefault<z.ZodString>;
      startServerReadyTimeout: z.ZodDefault<z.ZodNumber>;
      staticDirFileDiscoveryDepth: z.ZodDefault<z.ZodNumber>;
      staticDistDir: z.ZodOptional<z.ZodString>;
      url: z.ZodOptional<z.ZodArray<z.ZodString>>;
    }, z.core.$strip>>;
    server: z.ZodOptional<z.ZodObject<{
      basicAuth: z.ZodOptional<z.ZodObject<{
        password: z.ZodString;
        username: z.ZodString;
      }, z.core.$strip>>;
      logLevel: z.ZodDefault<z.ZodEnum<{
        silent: "silent";
        verbose: "verbose";
      }>>;
      port: z.ZodNumber;
      storage: z.ZodObject<{
        sqlConnectionSsl: z.ZodDefault<z.ZodBoolean>;
        sqlConnectionUrl: z.ZodString;
        sqlDangerouslyResetDatabase: z.ZodDefault<z.ZodBoolean>;
        sqlDatabasePath: z.ZodString;
        sqlDialect: z.ZodDefault<z.ZodEnum<{
          sqlite: "sqlite";
          postgres: "postgres";
          mysql: "mysql";
        }>>;
        sqlMigrationOptions: z.ZodObject<{
          tableName: z.ZodString;
        }, z.core.$strip>;
      }, z.core.$strip>;
    }, z.core.$strip>>;
    upload: z.ZodOptional<z.ZodIntersection<z.ZodDiscriminatedUnion<[z.ZodObject<{
      basicAuth: z.ZodOptional<z.ZodOptional<z.ZodObject<{
        password: z.ZodString;
        username: z.ZodString;
      }, z.core.$strip>>>;
      extraHeaders: z.ZodOptional<z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodString>>>;
      ignoreDuplicateBuildFailure: z.ZodOptional<z.ZodOptional<z.ZodBoolean>>;
      serverBaseUrl: z.ZodOptional<z.ZodDefault<z.ZodString>>;
      target: z.ZodNonOptional<z.ZodOptional<z.ZodLiteral<"lhci">>>;
      token: z.ZodOptional<z.ZodString>;
      urlReplacementPatterns: z.ZodOptional<z.ZodDefault<z.ZodArray<z.ZodString>>>;
    }, z.core.$strip>, z.ZodObject<{
      outputDir: z.ZodString;
      reportFilenamePattern: z.ZodDefault<z.ZodString>;
      target: z.ZodLiteral<"filesystem">;
    }, z.core.$strip>, z.ZodObject<{
      target: z.ZodLiteral<"temporary-public-storage">;
      uploadUrlMap: z.ZodDefault<z.ZodBoolean>;
    }, z.core.$strip>], "target">, z.ZodObject<{
      githubApiHost: z.ZodOptional<z.ZodDefault<z.ZodString>>;
      githubAppToken: z.ZodOptional<z.ZodOptional<z.ZodString>>;
      githubStatusContextSuffix: z.ZodOptional<z.ZodOptional<z.ZodString>>;
      githubToken: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    }, z.core.$strip>>>;
    wizard: z.ZodOptional<z.ZodObject<{
      extraHeaders: z.ZodOptional<z.ZodString>;
      serverBaseUrl: z.ZodOptional<z.ZodString>;
    }, z.core.$strip>>;
  }, z.core.$strip>;
}, z.core.$strip>;
export declare const lhciServerSchema: z.ZodObject<{
  basicAuth: z.ZodOptional<z.ZodObject<{
    password: z.ZodString;
    username: z.ZodString;
  }, z.core.$strip>>;
  logLevel: z.ZodDefault<z.ZodEnum<{
    silent: "silent";
    verbose: "verbose";
  }>>;
  port: z.ZodNumber;
  storage: z.ZodObject<{
    sqlConnectionSsl: z.ZodDefault<z.ZodBoolean>;
    sqlConnectionUrl: z.ZodString;
    sqlDangerouslyResetDatabase: z.ZodDefault<z.ZodBoolean>;
    sqlDatabasePath: z.ZodString;
    sqlDialect: z.ZodDefault<z.ZodEnum<{
      sqlite: "sqlite";
      postgres: "postgres";
      mysql: "mysql";
    }>>;
    sqlMigrationOptions: z.ZodObject<{
      tableName: z.ZodString;
    }, z.core.$strip>;
  }, z.core.$strip>;
}, z.core.$strip>;
export declare const lhciUploadSchema: z.ZodIntersection<z.ZodDiscriminatedUnion<[z.ZodObject<{
  basicAuth: z.ZodOptional<z.ZodOptional<z.ZodObject<{
    password: z.ZodString;
    username: z.ZodString;
  }, z.core.$strip>>>;
  extraHeaders: z.ZodOptional<z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodString>>>;
  ignoreDuplicateBuildFailure: z.ZodOptional<z.ZodOptional<z.ZodBoolean>>;
  serverBaseUrl: z.ZodOptional<z.ZodDefault<z.ZodString>>;
  target: z.ZodNonOptional<z.ZodOptional<z.ZodLiteral<"lhci">>>;
  token: z.ZodOptional<z.ZodString>;
  urlReplacementPatterns: z.ZodOptional<z.ZodDefault<z.ZodArray<z.ZodString>>>;
}, z.core.$strip>, z.ZodObject<{
  outputDir: z.ZodString;
  reportFilenamePattern: z.ZodDefault<z.ZodString>;
  target: z.ZodLiteral<"filesystem">;
}, z.core.$strip>, z.ZodObject<{
  target: z.ZodLiteral<"temporary-public-storage">;
  uploadUrlMap: z.ZodDefault<z.ZodBoolean>;
}, z.core.$strip>], "target">, z.ZodObject<{
  githubApiHost: z.ZodOptional<z.ZodDefault<z.ZodString>>;
  githubAppToken: z.ZodOptional<z.ZodOptional<z.ZodString>>;
  githubStatusContextSuffix: z.ZodOptional<z.ZodOptional<z.ZodString>>;
  githubToken: z.ZodOptional<z.ZodOptional<z.ZodString>>;
}, z.core.$strip>>;
export declare const lhciWizardSchema: z.ZodObject<{
  extraHeaders: z.ZodOptional<z.ZodString>;
  serverBaseUrl: z.ZodOptional<z.ZodString>;
}, z.core.$strip>;
// #endregion