/**
 * Generated by tsnapi — public API snapshot of `@stephansama/vite-iconify-svgmap/astro`
 */
// #region Default Export
declare function _default(_?: Options): AstroIntegration;
export default _default
// #endregion