/**
 * Generated by tsnapi — public API snapshot of `@stephansama/vite-iconify-svgmap`
 */
// #region Interfaces
export interface Options {
  dir?: string;
  root?: string | URL;
}
// #endregion

// #region Functions
export declare function writeSprites(_: string | URL): Promise<string[]>;
// #endregion

// #region Variables
export declare const VIRTUAL_MODULE_ID: string;
// #endregion

// #region Default Export
declare function _default(_?: Options): Plugin;
export default _default
// #endregion