/**
 * Generated by tsnapi — public API snapshot of `@stephansama/vite-iconify-svgmap/sveltekit`
 */
// #region Default Export
declare function _default(_?: Options): Plugin[];
export default _default
// #endregion