/**
 * Generated by tsnapi — public API snapshot of `@stephansama/typed-env`
 */
// #region Functions
export declare function createEnvironment<Schema extends StandardSchemaV1>(_: Schema, _?: dotenvx.DotenvConfigOptions | true): {
  generateExample(_: string): Promise<void>;
  loadEnv: (_?: dotenvx.DotenvConfigOptions) => dotenvx.DotenvConfigOutput;
  schema: Schema;
  validate({
    env: environment
  }?: {
    env?: Record<string, string | undefined>;
  }): Promise<StandardSchemaV1.InferOutput<Schema>>;
};
// #endregion