$schema: https://json-schema.org/draft/2020-12/schema
type: object
properties:
  affectedRegexes:
    default: []
    type: array
    items:
      type: string
  defaultLanguage:
    alias: l
    description: Default language to infer projects from
    default: JS
    type: string
    enum:
      - JS
      - RS
  disableEmojis:
    alias: e
    description: Whether or not to use emojis in markdown table headings
    default: false
    type: boolean
  disableMarkdownHeadings:
    description: Whether or not to display markdown headings
    default: false
    type: boolean
  enableToc:
    alias: t
    description: generate table of contents for readmes
    default: false
    type: boolean
  enableUsage:
    description: Whether or not to enable usage plugin
    default: false
    type: boolean
  headings:
    description: List of headings for different table outputs
    default:
      ACTION:
        - name
        - required
        - default
        - description
      PKG:
        - name
        - version
        - devDependency
      WORKSPACE:
        - name
        - version
        - downloads
        - description
      ZOD: []
    type: object
    propertyNames:
      description: Comment action options
      type: string
      enum:
        - ACTION
        - PKG
        - USAGE
        - WORKSPACE
        - ZOD
    additionalProperties:
      type: array
      items:
        description: Table heading options
        type: string
        enum:
          - default
          - description
          - devDependency
          - downloads
          - name
          - private
          - required
          - version
  onlyReadmes:
    alias: r
    description: Whether or not to only traverse readmes
    default: true
    type: boolean
  onlyShowPublicPackages:
    alias: p
    description: Only show public packages in workspaces
    default: false
    type: boolean
  removeScope:
    description: Remove common workspace scope
    default: ""
    type: string
  templates:
    description: Handlebars templates used to fuel list and table generation
    default:
      downloadImage: https://img.shields.io/npm/dw/{{name}}?labelColor=211F1F
      emojis:
        default: ⚙️
        description: 📝
        devDependency: 💻
        downloads: 📥
        name: 🏷️
        private: 🔒
        required: ""
        version: ""
      registryUrl: https://www.npmjs.com/package/{{name}}
      versionImage: https://img.shields.io/npm/v/{{uri_name}}?logo=npm&logoColor=red&color=211F1F&labelColor=211F1F
    type: object
    properties:
      downloadImage:
        default: https://img.shields.io/npm/dw/{{name}}?labelColor=211F1F
        type: string
      emojis:
        default:
          default: ⚙️
          description: 📝
          devDependency: 💻
          downloads: 📥
          name: 🏷️
          private: 🔒
          required: ""
          version: ""
        description: Table heading emojis used when enabled
        type: object
        propertyNames:
          description: Table heading options
          type: string
          enum:
            - default
            - description
            - devDependency
            - downloads
            - name
            - private
            - required
            - version
        additionalProperties:
          type: string
      registryUrl:
        default: https://www.npmjs.com/package/{{name}}
        type: string
      versionImage:
        default: https://img.shields.io/npm/v/{{uri_name}}?logo=npm&logoColor=red&color=211F1F&labelColor=211F1F
        type: string
    required:
      - downloadImage
      - emojis
      - registryUrl
      - versionImage
    additionalProperties: false
  tocHeading:
    description: Markdown heading used to generate table of contents
    default: Table of contents
    type: string
  usageFile:
    description: Workspace level usage file
    default: ""
    type: string
  usageHeading:
    description: Markdown heading used to generate usage example
    default: Usage
    type: string
  verbose:
    alias: v
    description: whether or not to display verbose logging
    default: false
    type: boolean
required:
  - affectedRegexes
  - defaultLanguage
  - disableEmojis
  - disableMarkdownHeadings
  - enableToc
  - enableUsage
  - headings
  - onlyReadmes
  - onlyShowPublicPackages
  - removeScope
  - templates
  - tocHeading
  - usageFile
  - usageHeading
  - verbose
additionalProperties: false
