/**
 * Generated by tsnapi — public API snapshot of `@stephansama/astro-iconify-svgmap/get`
 */
// #region Functions
export declare function getIcon(_: string, _: string): Promise<string>;
// #endregion