/**
 * Generated by tsnapi — public API snapshot of `@stephansama/astro-iconify-svgmap`
 */
// #region Functions
export declare function createIntegration(_?: Options): AstroIntegration;
// #endregion

// #region Default Export
declare function _default(_?: Options): Plugin;
export default _default
// #endregion