/**
 * Generated by tsnapi — public API snapshot of `@stephansama/multipublish/schema`
 */
// #region Types
export type Config = z.input<typeof configSchema>;
export type JsrPlatformOptionsSchema = z.infer<typeof jsrPlatformOptionsSchema>;
export type NpmPlatformOptionsSchema = z.infer<typeof npmPlatformOptionsSchema>;
export type PlatformsSchema = z.input<typeof platformsSchema>;
// #endregion

// #region Variables
export declare const configSchema: z.ZodObject<{
  platforms: z.ZodArray<z.ZodUnion<[z.ZodUnion<[z.ZodUnion<[z.ZodLiteral<"jsr">, z.ZodLiteral<"npm">]>, z.ZodTuple<[z.ZodLiteral<"jsr">, z.ZodObject<{
    allowSlowTypes: z.ZodDefault<z.ZodBoolean>;
    defaultExclude: z.ZodOptional<z.ZodArray<z.ZodString>>;
    defaultInclude: z.ZodOptional<z.ZodArray<z.ZodString>>;
    experimentalGenerateJSR: z.ZodDefault<z.ZodBoolean>;
    experimentalUpdateCatalogs: z.ZodDefault<z.ZodBoolean>;
    tokenEnvironmentKey: z.ZodDefault<z.ZodString>;
  }, z.core.$strip>], null>]>, z.ZodTuple<[z.ZodLiteral<"npm">, z.ZodObject<{
    registry: z.ZodDefault<z.ZodString>;
    strategy: z.ZodDefault<z.ZodEnum<{
      ".npmrc": ".npmrc";
      "package.json": "package.json";
    }>>;
    tokenEnvironmentKey: z.ZodDefault<z.ZodString>;
  }, z.core.$strip>], null>]>>;
  tmpDirectory: z.ZodDefault<z.ZodString>;
  useChangesets: z.ZodDefault<z.ZodBoolean>;
}, z.core.$strip>;
export declare const jsrPlatformOptionsSchema: z.ZodObject<{
  allowSlowTypes: z.ZodDefault<z.ZodBoolean>;
  defaultExclude: z.ZodOptional<z.ZodArray<z.ZodString>>;
  defaultInclude: z.ZodOptional<z.ZodArray<z.ZodString>>;
  experimentalGenerateJSR: z.ZodDefault<z.ZodBoolean>;
  experimentalUpdateCatalogs: z.ZodDefault<z.ZodBoolean>;
  tokenEnvironmentKey: z.ZodDefault<z.ZodString>;
}, z.core.$strip>;
export declare const npmPlatformOptionsSchema: z.ZodObject<{
  registry: z.ZodDefault<z.ZodString>;
  strategy: z.ZodDefault<z.ZodEnum<{
    ".npmrc": ".npmrc";
    "package.json": "package.json";
  }>>;
  tokenEnvironmentKey: z.ZodDefault<z.ZodString>;
}, z.core.$strip>;
export declare const platformsSchema: z.ZodArray<z.ZodUnion<[z.ZodUnion<[z.ZodUnion<[z.ZodLiteral<"jsr">, z.ZodLiteral<"npm">]>, z.ZodTuple<[z.ZodLiteral<"jsr">, z.ZodObject<{
  allowSlowTypes: z.ZodDefault<z.ZodBoolean>;
  defaultExclude: z.ZodOptional<z.ZodArray<z.ZodString>>;
  defaultInclude: z.ZodOptional<z.ZodArray<z.ZodString>>;
  experimentalGenerateJSR: z.ZodDefault<z.ZodBoolean>;
  experimentalUpdateCatalogs: z.ZodDefault<z.ZodBoolean>;
  tokenEnvironmentKey: z.ZodDefault<z.ZodString>;
}, z.core.$strip>], null>]>, z.ZodTuple<[z.ZodLiteral<"npm">, z.ZodObject<{
  registry: z.ZodDefault<z.ZodString>;
  strategy: z.ZodDefault<z.ZodEnum<{
    ".npmrc": ".npmrc";
    "package.json": "package.json";
  }>>;
  tokenEnvironmentKey: z.ZodDefault<z.ZodString>;
}, z.core.$strip>], null>]>>;
// #endregion