/**
 * Generated by tsnapi — public API snapshot of `@stephansama/auto-readme/schema`
 */
// #region Types
export type Config = Partial<z.infer<typeof _configSchema>>;
// #endregion

// #region Variables
export declare const actionsSchema: z.ZodEnum<{
  ACTION: "ACTION";
  PKG: "PKG";
  USAGE: "USAGE";
  WORKSPACE: "WORKSPACE";
  ZOD: "ZOD";
}>;
export declare const configSchema: z.ZodOptional<z.ZodObject<{
  affectedRegexes: z.ZodArray<z.ZodString>;
  collapseHeadings: z.ZodArray<z.ZodString>;
  defaultLanguage: z.ZodDefault<z.ZodEnum<{
    JS: "JS";
    RS: "RS";
  }>>;
  disableEmojis: z.ZodDefault<z.ZodBoolean>;
  disableMarkdownHeadings: z.ZodDefault<z.ZodBoolean>;
  enablePrettier: z.ZodDefault<z.ZodBoolean>;
  enableToc: z.ZodDefault<z.ZodBoolean>;
  enableUsage: z.ZodDefault<z.ZodBoolean>;
  headings: z.ZodDefault<z.ZodOptional<z.ZodDefault<z.ZodRecord<z.ZodEnum<{
    ACTION: "ACTION";
    PKG: "PKG";
    USAGE: "USAGE";
    WORKSPACE: "WORKSPACE";
    ZOD: "ZOD";
  }>, z.ZodOptional<z.ZodArray<z.ZodEnum<{
    description: "description";
    default: "default";
    devDependency: "devDependency";
    downloads: "downloads";
    name: "name";
    private: "private";
    required: "required";
    version: "version";
  }>>>>>>>;
  onlyReadmes: z.ZodDefault<z.ZodBoolean>;
  onlyShowPublicPackages: z.ZodDefault<z.ZodBoolean>;
  removeScope: z.ZodDefault<z.ZodString>;
  templates: z.ZodDefault<z.ZodOptional<z.ZodObject<{
    downloadImage: z.ZodDefault<z.ZodString>;
    emojis: z.ZodDefault<z.ZodRecord<z.ZodEnum<{
      description: "description";
      default: "default";
      devDependency: "devDependency";
      downloads: "downloads";
      name: "name";
      private: "private";
      required: "required";
      version: "version";
    }>, z.ZodString>>;
    registryUrl: z.ZodDefault<z.ZodString>;
    versionImage: z.ZodDefault<z.ZodString>;
  }, z.core.$strip>>>;
  tocHeading: z.ZodDefault<z.ZodString>;
  usageFile: z.ZodDefault<z.ZodString>;
  usageHeading: z.ZodDefault<z.ZodString>;
  verbose: z.ZodDefault<z.ZodBoolean>;
}, z.core.$strip>>;
export declare const defaultTableHeadings: Record<"ACTION" | "PKG" | "USAGE" | "WORKSPACE" | "ZOD", ("description" | "default" | "devDependency" | "downloads" | "name" | "private" | "required" | "version")[] | undefined>;
export declare const defaultTemplates: {
  downloadImage: string;
  emojis: Record<"description" | "default" | "devDependency" | "downloads" | "name" | "private" | "required" | "version", string>;
  registryUrl: string;
  versionImage: string;
};
export declare const formatsSchema: z.ZodDefault<z.ZodEnum<{
  LIST: "LIST";
  TABLE: "TABLE";
}>>;
export declare const languageSchema: z.ZodDefault<z.ZodEnum<{
  JS: "JS";
  RS: "RS";
}>>;
// #endregion