/**
 * Generated by tsnapi — public API snapshot of `@stephansama/anchor-pnpm`
 */
// #region Functions
export declare function add(_: Document, _: string, _: string): {
  added: boolean;
};
export declare function list(_: Document): AnchorEntry[];
export declare function loadWorkspace(_: string): Promise<Document.Parsed>;
export declare function remove(_: Document, _: string, _?: {
  force?: boolean;
}): {
  dangling: string[];
  removed: boolean;
};
export declare function resolveWorkspacePath(_?: string): Promise<string>;
export declare function saveWorkspace(_: string, _: Document): Promise<void>;
export declare function sync(_: Document): SyncProposal[];
export declare function update(_: Document, _: string, _: string): {
  updated: boolean;
};
// #endregion